Import('conf')
Import('dirs')

samiam = conf.env.Program('samiam', 'samiam.c', LIBS='sam')
conf.env.Install(dirs['install']['bin'], samiam)
Depends(samiam, dirs['build']['lib'] + '/libsam' + conf.env['SHLIBSUFFIX'])
