Import('conf')
Import('dirs')
Import('libsam')
Import('i18n')

sources = [
    'execute.c',
    'samiam.c',
]
domain = 'samiam'

if conf.CheckFunc('getopt_long'):
    sources += ['parse_options_gnu.c']
elif conf.CheckFunc('getopt'):
    sources += ['parse_options_bsd.c']
else:
    sources += ['parse_options_plain.c']

conf.env['PACKAGE'] = domain
conf.env['POTFILE'] = domain + '.pot'

i18n(conf.env, sources)
samiam = conf.env.Program('samiam', sources, LIBS='sam')
Alias('install', conf.env.Install(dirs['install']['bin'], samiam))
Depends(samiam, libsam)
