#!/bin/sh

set -e

name=`basename $PWD`
version=`cat VERSION`
tmpdir="/tmp/rpm"

if ! grep _topdir $HOME/.rpmmacros 2>/dev/null >/dev/null; then
    echo "%_topdir $tmpdir" >>$HOME/.rpmmacros
fi

rm -Rf $tmpdir
mkdir -p $tmpdir/{BUILD,SOURCES,SPECS,RPMS,SRPMS,tmp}
cp scripts/samiam.spec $tmpdir/SPECS
if [ ! -f ../$name-version.tar.gz ]; then
    scripts/dist
fi
cp ../$name-$version.tar.gz $tmpdir/SOURCES

(cd $tmpdir &&
 rpmbuild -ba SPECS/samiam.spec)

cp $tmpdir/SRPMS/* $tmpdir/RPMS/*/* ..
rm -Rf $tmpdir
