import os

Import('conf')
Import('dirs')
Import('version')
Import('i18n')

conf.CheckLib('dl')
conf.CheckLib('intl')

domain = 'libsam'
sources = [
	'array.c',
	'error.c',
	'es.c',
	'execute_types.c',
	'hash_table.c',
	'io.c',
	'opcode.c',
	'parse.c',
	'string.c',
	'util.c',
]

conf.env.Append(PACKAGE=domain)
conf.env.Append(POTFILE=domain + '.pot')

conf.env.Append(LIBS=['c', 'm'])
i18n(conf.env, sources)
libsam = conf.env.SharedLibrary('sam', sources)

# TODO: portable
Alias('install',
      conf.env.InstallAs(os.path.join(dirs['install']['lib'],
			 'libsam' + conf.env['SHLIBSUFFIX'] + '.' + version),
			 libsam))
SConscript(['../samiam/SConscript'], ['conf', 'dirs', 'libsam', 'i18n'])
