Import('conf')
Import('dirs')
Import('version')

conf.CheckLib('dl')
libsam = conf.env.SharedLibrary('sam', [
	'array.c',
	'error.c',
	'es.c',
	'execute.c',
	'execute_types.c',
	'hash_table.c',
	'io.c',
	'main.c',
	'opcode.c',
	'parse.c',
	'string.c',
	'util.c',
])
conf.env.Append(LIBS=['c', 'm'])

# Yeah, it's not even portable.
Alias('install', conf.env.InstallAs(dirs['install']['lib'] + '/libsam' + conf.env['SHLIBSUFFIX'] + '.' + version, libsam))
SConscript(['../samiam/SConscript'], ['conf', 'dirs', 'libsam'])
