Import('ccflags')
Import('dirs')

conf = Configure(
    Environment(CCFLAGS=ccflags,
		CPPPATH='../include',
		LIBPATH=dirs['build']['lib']
))
if conf.CheckCHeader('sys/mman.h'):
    conf.env.Append(CCFLAGS=' -DHAVE_MMAN_H')
if conf.CheckCHeader('dlfcn.h'):
    conf.env.Append(CCFLAGS=' -DHAVE_DLFCN_H')
if conf.CheckCHeader('unistd.h'):
    conf.env.Append(CCFLAGS=' -DHAVE_UNISTD_H')
if conf.CheckCHeader('locale.h'):
    conf.env.Append(CCFLAGS=' -DHAVE_LOCALE_H')

SConscript(['libsam/SConscript'], ['conf', 'dirs'])
SConscript(['samiam/SConscript'], ['conf', 'dirs'])
env = conf.Finish()
